# Site settings
course_name: Intorduction to Computer Vision
course_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ornare aliquam mattis. Donec hendrerit sollicitudin urna. Aliquam venenatis rutrum velit, at lobortis dui cursus a. Nam varius metus in turpis maximus, ut rhoncus tellus dictum. In aliquam tortor nec mi dapibus, sit amet vehicula dolor auctor."
course_semester: "Spring 2022"

baseurl: "/pku_cv_intro" # the subpath of your site, e.g. /blog/
url: "https://dakenam.github.io/pku_cv_intro/" # the base hostname & protocol for your site

schoolname: "Peking University"
schoolurl: "https://www.pku.edu.cn/"
#twitter_username: username 

address: |
    School of Electronics Engineering and Computer Science
    Peking University
    Beijing, China

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
