# Site settings
course_name: Robot Vision and Learning - From a Perspective of Embodied AI
course_description: "The research and development of robotic and unmanned systems, e.g.  home robots and autonomous vehicles, is a frontier field in computer science and artificial intelligence paving the path to artificial general intelligence (AGI). In recent years,  deep learning based 3D vision systems and reinforcement learning algorithms have achieved a number of breakthroughs, spawning the emerging field -- embodied artificial intelligence, and generating many new directions and topics worthy of in-depth investigation. Therefore, we offer this advanced graduate-level course for students with backgrounds in deep learning and computer vision to further their study in 3D vision and robot learning. The course will cover various tasks and problems ranging from the construction of robot vision systems to vision-based robot control and interaction, and aims to offer deep and broad discussion of this cutting-edge field."
course_semester: "Fall 2023"

baseurl: "/RVAL" # the subpath of your site, e.g. /blog/
url: "https://hughw19.github.io/" # the base hostname & protocol for your site

schoolname: "Peking University"
schoolurl: "https://www.pku.edu.cn/"
#twitter_username: username 

address: |
    Center on Frontiers of Computing Studies, 
    School of Computer Science,
    Peking University,
    Beijing, China

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
